### ISSUE TITLE
Set default values manually

### ISSUE THREAD

**Issue by jlelse** [afollestad/json#1]
When I use any of this get...() methods or the get() method itself I'll get back null for a not existing string, 0 for not existing int and so on right? Is it possible to submit a default value so that I get 1 when the int doesn't exist?
But the library is awesome!

**Comment by afollestad** [comment]
Now available in 0.1.1

# Retrieving Values from Objects

Various methods exist for retrieving existing values (default values are returned if they don't exist). The one parameter 
version uses whatever the usual default of a type is (0 for number types, null for everything else), if the no value is found 
for the key. The two parameter version lets you specify a custom default.

```java
Json json = // ...

String str = json.getString("name");
String strWithDefault = json.getString("name", null);

boolean bool = json.getBool("name");
boolean boolWithDefault = json.getBool("name", true);

short shrt = json.getShort("name");
short shrtWithDefault = json.getShort("name", (short)0);

int integer = json.getInt("name");
int integerWithDefault = json.getInt("name", 0);

long lng = json.getLong("name");
long lngWithDefault = json.getLong("name", 0L);

float flt = json.getFloat("name");
float fltWithDefault = json.getFloat("name", 0f);

double doub = json.getDouble("name");
double doubWithDefault = json.getDouble("name", 0d);

Json obj = json.getJsonObject("name");
JsonArray ary = json.getJsonArray("name");
```

Further, the `get(String)` method will actually automatically cast its return value to whatever variable you're setting it to:

```java
String str = json.get("name");
long lng = json.get("name");
```

It will also infer its type if you pass a default value, removing the need to use explicit `get[Type]` methods:

```java
if (json.get("name", false)) {
    // do something
}
```

**Comment by W88MYR** [comment]
True

**Comment by W88MYR** [comment]
1
